### ISSUE TITLE
Should this just be `python -m trustme`?

### ISSUE THREAD

**Issue by njsmith** [sethmlarson/trustme-cli#1]
Hey, @pquentin just pointed me to this. Very neat!
 
If you think it's more fun to maintain your own thing that's cool, but I wonder if it would make sense to consolidate the code in one repo :-)

**Comment by sethmlarson** [comment]
Let's consolidate! :heart: I'll open a PR.

**Comment by sethmlarson** [comment]
This is complete now, only pending a release of `trustme`.
